AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer

Parameters:
  Environment:
    Type: String
  VpcId:
    Type: String
  PublicSubnetIds:
    Type: CommaDelimitedList

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Allow HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Environment}-alb"
      Scheme: internet-facing
      Subnets: !Ref PublicSubnetIds
      SecurityGroups: [!Ref ALBSecurityGroup]
      Type: application

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: 'Not Found'

Outputs:
  ALBArn:
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub "${Environment}-ALBArn"

  ALBDNS:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${Environment}-ALBDNS"

  ListenerArn:
    Value: !Ref Listener
    Export:
      Name: !Sub "${Environment}-ListenerArn"
