AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Roles para ECS e GitHub Actions

Parameters:
  Environment:
    Type: String
  AccountId:
    Type: String

Resources:
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-ECSExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-GitHubActionsRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHub.Repository}:ref:refs/heads/main"
      Policies:
        - PolicyName: GitHubActionsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

Outputs:
  ECSExecutionRoleArn:
    Value: !GetAtt ECSExecutionRole.Arn
    Export:
      Name: !Sub "${Environment}-ECSExecutionRole"

  GitHubActionsRoleArn:
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: !Sub "${Environment}-GitHubActionsRole"
