name: Deploy Homologation and Create Release

on:
  push:
    branches:
      - homologation

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy-and-create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Infra Homologation
        run: echo "Deploy infra homologation aqui"

      - name: Get Next Version
        id: get_version
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$latest_tag" ]; then
            next_version="1.0.0"
          else
            version_core=${latest_tag#v}
            major=$(echo $version_core | cut -d. -f1)
            minor=$(echo $version_core | cut -d. -f2)
            patch=$(echo $version_core | cut -d. -f3)
            patch=$((patch + 1))
            next_version="${major}.${minor}.${patch}"
          fi
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      - name: Create Release Branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release-${{ env.NEXT_VERSION }}
          git push origin release-${{ env.NEXT_VERSION }}
