name: Validate Infra and Promote to Development

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate CloudFormation
        run: |
          for template in cloudformation/*.yml; do
            echo "Validating $template"
            aws cloudformation validate-template --template-body file://$template || exit 1
          done

      - name: Create Pull Request to Development
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Promote Feature -> Development'
          body: 'Automated PR from feature to development.'
          base: development
          branch: ${{ github.ref_name }}
